# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhBackup < Formula
  desc "A simple CLI utility, written in GoLang, to backup all of your public GitHub repos."
  homepage "https://github.com/ChrisWiegman/gh-backup"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ChrisWiegman/gh-backup/releases/download/1.0.1/gh-backup_macos_arm64.zip"
      sha256 "90d05d20d082fcb37f6eb5eff3bbdf35a690ccb160723d6fff10d9aa0a34d76e"

      def install
        bin.install "gh-backup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ChrisWiegman/gh-backup/releases/download/1.0.1/gh-backup_macos_x86_64.zip"
      sha256 "7d05c706c4862f1c3feb93091b62867bbac626d2ed68eec025d1c3fe6f0c349f"

      def install
        bin.install "gh-backup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ChrisWiegman/gh-backup/releases/download/1.0.1/gh-backup_linux_x86_64.zip"
      sha256 "3bf61afd7f4dde368b24f4999cfd2cf092d6dd329cd64f070d91c53f08c8d4f0"

      def install
        bin.install "gh-backup"
      end
    end
  end

  test do
    system "#{bin}/gh-backup --version"
  end
end
