# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhBackup < Formula
  desc "A simple CLI utility, written in GoLang, to backup all of your public GitHub repos."
  homepage "https://github.com/ChrisWiegman/gh-backup"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ChrisWiegman/gh-backup/releases/download/1.0.3/gh-backup_macos_x86_64.zip"
      sha256 "a55919bc041f451a3960b1eea74b4b5162c7a503ff34f78ef620fabf9bb6a6ab"

      def install
        bin.install "gh-backup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ChrisWiegman/gh-backup/releases/download/1.0.3/gh-backup_macos_arm64.zip"
      sha256 "6c074cd47ebf1c89bbee3b9eda31b76aa38b0e0d5d242d9a7934ee455ec0be04"

      def install
        bin.install "gh-backup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ChrisWiegman/gh-backup/releases/download/1.0.3/gh-backup_linux_x86_64.zip"
      sha256 "99c9cdf6832043c6ccad8a5f9244f023ac0a1d0b77bb88a8bfaf1fb2eba47b14"

      def install
        bin.install "gh-backup"
      end
    end
  end

  test do
    system "#{bin}/gh-backup --version"
  end
end
