# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhBackup < Formula
  desc "A simple CLI utility, written in GoLang, to backup all of your public GitHub repos."
  homepage "https://github.com/ChrisWiegman/gh-backup"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ChrisWiegman/gh-backup/releases/download/1.0.0/gh-backup_macos_arm64.zip"
      sha256 "8ff36ab408e185ea4f0789c4f729cdb55498213ff7d33858574b57556be45c21"

      def install
        bin.install "gh-backup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ChrisWiegman/gh-backup/releases/download/1.0.0/gh-backup_macos_x86_64.zip"
      sha256 "819772f543148d7e762ac5d2eec07571fd4783e4a1eb46569acb15f96e8207e6"

      def install
        bin.install "gh-backup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ChrisWiegman/gh-backup/releases/download/1.0.0/gh-backup_linux_x86_64.zip"
      sha256 "960466064170745bfc9ecdfc3161824056e783e71aff11e441b36f8389abb544"

      def install
        bin.install "gh-backup"
      end
    end
  end

  test do
    system "#{bin}/gh-backup --version"
  end
end
